### ISSUE TITLE
Email address with a + makes user invalid

### ISSUE THREAD

**Issue by sarahmei** [diaspora/diaspora#3046]
Somehow we had someone register with an email address with a + in it (e.g. username+disposabletext@gmail.com). Now they can't change anything in their user settings. The error message is "email address is already taken." I checked, though, and there are no other users with that email (either with or without the disposable text). 

When I changed the email address to just username@gmail.com, everything was cool.

**Comment by svbergerem** [comment]
I changed the email address of a user on my dev pod to te+st@us.er6. After following the link I found in the logs to activate the email address I was still able to change my name (profile settings) and language (account settings). The email address in the database is te+st@us.er6.

To me it looks like this bug has been fixed.

**Comment by svbergerem** [comment]
Also tested signing up on my dev pod using an email address with a +. Everything seems to work.

**Comment by nado** [comment]
Hi, the pod (https://framasphere.org) I am using just updated to 0.6.0 and this bug is still present at login. I have to use the inspect functionnality of chromium to add a + in the pattern attribute of the html input.

**Comment by SansPseudoFix** [comment]
@nado actually, you don't need to enter your email adress to log in: only your username (so, if your username is nado@framasphere.org, you have to enter nado and your password).

**Comment by nado** [comment]
Oh, right, it doesnt work with the "@pod" but nado alone works :) Thx for the help.
