### ISSUE TITLE
Bug. I can't "like" on single post view. My acct is on Diasp.org. I *can* "like" on stream or activity.

### ISSUE THREAD

**Issue by jjoe** [diaspora/diaspora#5486]

**Comment by svbergerem** [comment]
@jjoe: do you have any additional information?

**Comment by jjoe** [comment]
Sorry I took so long to respond. It still happens. When I click the single post view heart icon, nothing happens. I can only "like" on stream, activity, etc. I am on diasp.org. I couldn't "like" this post from SPV just now: https://diasp.org/posts/30ae78c0e9cd0132d8f776a9846f8967
I am easier to reach at   https://diasp.org/people/6fb71698d1dc0e20 than on email. Thanks for responding.

Date: Sun, 3 May 2015 08:21:42 -0700

**Comment by jjoe** [comment]
...Commenting and resharing seem to work okay on SPV. It's just the heart icon that doesn't.

From: saxophonejoe@live.com
To: reply@reply.github.com
Subject: RE: [diaspora] Bug. I can't "like" on single post view. My acct is on Diasp.org. I *can* "like" on stream or activity. (#5486)
Date: Sun, 31 May 2015 23:40:53 -0500




Sorry I took so long to respond. It still happens. When I click the single post view heart icon, nothing happens. I can only "like" on stream, activity, etc. I am on diasp.org. I couldn't "like" this post from SPV just now: https://diasp.org/posts/30ae78c0e9cd0132d8f776a9846f8967
I am easier to reach at   https://diasp.org/people/6fb71698d1dc0e20 than on email. Thanks for responding.

Date: Sun, 3 May 2015 08:21:42 -0700

**Comment by SuperTux88** [comment]
I think this was fixed with #5978 ? I didn't know that there was a bug for this.

**Comment by jhass** [comment]
Might be, it's still hard to tell what's the exact error here.

**Comment by SuperTux88** [comment]
The linked post (https://diasp.org/posts/30ae78c0e9cd0132d8f776a9846f8967) is one with a guid (which was the cause of the bug)  and diasp.org doesn't have the fix yet, so its still broken there. But its fixed in develop/stable.

It should be possible to like the same post with id: https://diasp.org/posts/4480697

**Comment by jhass** [comment]
Alright, @jjoe say something if ^ doesn't work for you either and we'll reopen.

**Comment by jjoe** [comment]
Okay I can like and unlike on  https://diasp.org/posts/4480697 but on 
https://diasp.org/posts/30ae78c0e9cd0132d8f776a9846f8967 ,I can UNLIKE but still cannot like. Weird.
But still,  when I click the date/time on a post on my stream, I get the longer id.
Date: Mon, 1 Jun 2015 04:14:05 -0700

**Comment by jhass** [comment]
Yes, the fix isn't released yet, so you don't have it on diasp.org.

**Comment by jjoe** [comment]
OH wait! I take back that last sentence. It appears to be fixed now. I get the shorter id now. Another post that was giving me a 404 on spv seems to be fixed too.
From: saxophonejoe@live.com
To: reply@reply.github.com
Subject: RE: [diaspora] Bug. I can't "like" on single post view. My acct is on Diasp.org. I *can* "like" on stream or activity. (#5486)
Date: Wed, 3 Jun 2015 02:45:17 -0500




Okay I can like and unlike on  https://diasp.org/posts/4480697 but on 
https://diasp.org/posts/30ae78c0e9cd0132d8f776a9846f8967 ,I can UNLIKE but still cannot like. Weird.
But still,  when I click the date/time on a post on my stream, I get the longer id.
Date: Mon, 1 Jun 2015 04:14:05 -0700

**Comment by jjoe** [comment]
My greasemonkey "podsavelink" seems to be disabled now. It provided a guid # for cross pod sharing. I think it might have been the source of the problem. Do you think there is any way to re-enable it without causing further problems?

**Comment by Flaburgan** [comment]
As said, your problem (not being able to like with the full id) is fixed in the next minor version, to be released the 14th of June.

**Comment by jjoe** [comment]
Thank you! As always, diaspora devs are the best!
