### ISSUE TITLE
Likes and reshares by users that the author has ignored show up on authors original post

### ISSUE THREAD

**Issue by KentShikama** [diaspora/diaspora#6929]

**Comment by ABISprotocol** [comment]
Of course they can, because they are public.  

Please see my extended commentary on this issue here:
https://github.com/diaspora/diaspora/issues/1734#issuecomment-235160532

**Comment by KentShikama** [comment]
I'm wondering if likes and reshares are relayed from the author's pod (not directly from the blocked user) just like comments are.

**Comment by SuperTux88** [comment]
Comments and Likes are fixed with #6873, Reshares can't be blocked, because they are new posts by the ignored person, which you can't delete.

**Comment by KentShikama** [comment]
@SuperTux88 Sure but reshares by the blocked user can be hidden from the original post right?

Graphically, this wouldn't be showing up (assuming that is the blocked user):

![screen shot 2016-07-26 at 5 47 44 pm](https://cloud.githubusercontent.com/assets/6329898/17131591/21bdcefe-5359-11e6-9f09-22df20b69281.png)

**Comment by SuperTux88** [comment]
No ... or yes, but only on your pod, so everybody else can still see it.

**Comment by SuperTux88** [comment]
Also, this would be weird for other users on your pod, when they can see the reshare, but don't see the avatar on the post. So maybe only hide it for you, if that is what you want?

**Comment by KentShikama** [comment]
@SuperTux88 Everyone else can still see the reshared post but they all can't see the fact that it is a reshare right? Here is my understanding (guess) of the federation:

User A makes a post on pod A
User B reshares post on pod B
The fact that User B has reshared is relayed back to pod A which relays to all other pods that User B has reshared
The actual post is relayed as a new post by pod B to all other pods

**Comment by SuperTux88** [comment]
No, reshares are not relayed, they are new posts from the user B, that link to the post from user A. So all people on pods where user B has contacts can see the reshare (and the fact that user B has reshared it).

**Comment by KentShikama** [comment]
Ahh ok interesting. Thanks for the explanation. I'll close this since there doesn't seem to be a simple solution here.
